---
- name: setup | all Ansible-user config
  hosts: all
  vars_files:
    - customize.yml
  user: "{{ username }}"
  sudo: true
  tasks:
  - name: install some Dev packages
    apt: pkg={{ item }} state=latest
         update_cache=yes  cache_valid_time=3600
    with_items:
    - vim
    - emacs24-nox
    - screen
    - libxslt1-dev

- name: install DevStack
  hosts: all
  vars_files:
    - customize.yml
  remote_user: "{{ username }}"
  tasks:

  - name: git-clone DevStack
    git: repo=https://github.com/openstack-dev/devstack.git
         dest=~/devstack
         version={{ branch }}

  - name: deploy DevStack 'local.conf'
    template: src=templates/devstack-local.conf.j2
              dest=~/devstack/local.conf

  - name: run stack.sh to deploy DevStack
    command: chdir=~/devstack ./stack.sh
    ignore_errors: yes

  - name: re-install cinder requirements
    command: pip install --upgrade -r /opt/stack/cinder/requirements.txt
    sudo: yes

  - name: unstack it
    command: chdir=~/devstack ./unstack.sh

  - name: restack it
    command: chdir=~/devstack ./stack.sh
